--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/pjz9n-pm-pl/Mission
build-by-default: true
branches:
  - issues/40
projects:
  Mission:
    icon: icon.png
    libs:
      - src: dktapps-pm-pl/pmforms/pmforms
        version: 1.0.0
      - src: CortexPE/Commando/Commando
        version: 2.1.1
...
