--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/pjz9n-pm-pl/Mission
build-by-default: true
branches:
  - master
projects:
  Mission:
    lib:
      - src: dktapps-pm-pl/pmforms/pmforms
          version: 1.0.0
      - src: pjz9n-pm-pl/pmforms-addon/pmforms-addon
          version: 1.0.0
      - src: CortexPE/Commando/Commando
          version: 2.1.1
...
