name: Mission
version: 1.8.1
main: pjz9n\mission\Main
api: 3.4.0

softdepend:
  - Mineflow
  - ScoreHud

permissions:
  mission.command.mission:
    default: true
  mission.command.mission.edit:
    default: op
  mission.command.mission.setting:
    default: op
  mission.command.mission.list:
    default: true
  mission.command.mission.info:
    default: op
